modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"


[[mods]]
    modId="morecreatestuffs"
    version="mc1.16-1.4.1"
    displayName="More Create Stuffs"
    logoFile="icon.png"
    authors="JerryLu086"
    description='''
This mod added some items, recipes related to other mods to do the ore processing from Create.
'''

[[dependencies.morecreatestuffs]]
    modId="create"
    mandatory=true
    versionRange="NONE"
    side="BOTH"
